### ISSUE TITLE
can not install the package

### ISSUE THREAD

**Issue by Jiangchao3** [cordmaur/Sentinel1-Flood-Finder#2]
Hi @cordmaur , many thanks for deleveloping such an interesting and useful tool, but i can not install it on my system, I work on a linux system, it shows some errors as following when i use the commond line you recommend to install:

Would it be possible provide some suggestions to adress it? Manyt thanks.

Jiangchao

Collecting git+https://github.com/cordmaur/Sentinel1-Flood-Finder.git@main
  Cloning https://github.com/cordmaur/Sentinel1-Flood-Finder.git (to revision main) to /tmp/pip-req-build-2t8vxny6
  Running command git clone --filter=blob:none --quiet https://github.com/cordmaur/Sentinel1-Flood-Finder.git /tmp/pip-req-build-2t8vxny6
  Resolved https://github.com/cordmaur/Sentinel1-Flood-Finder.git to commit 8271035c8dc728d38655829e7c49aa7c51055caa
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [11 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-2t8vxny6/setup.py", line 6, in <module>
          import flood_finder  # pylint: disable=E0401, C0413
          ^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-req-build-2t8vxny6/src/flood_finder/__init__.py", line 5, in <module>
          from .imagery import ImageFinder, S1Imagery
        File "/tmp/pip-req-build-2t8vxny6/src/flood_finder/imagery.py", line 6, in <module>
          import matplotlib.pyplot as plt
      ModuleNotFoundError: No module named 'matplotlib'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by Jiangchao3** [comment]
hi @cordmaur , now i have successfully install the s1floodfinder package on my system after first install all the required python libraries you list in the requirment.txt file.

But one thing I have to point out is that, the scikit-image==1.2.2 seems wrong, because scikit-learn have the version 1.2.2, but scikit-image don't, the latest scikit-image is 0.24.0. Please check.

I will start to test the package, and i will let you know more detail once i finished.

**Comment by Jiangchao3** [comment]
hi @cordmaur, when i try to run the 01-introduction.ipynb, 

for the following script
processor = FloodProcessor(
    aoi_df = gdf,
    output_dir='../tmp',
    # subscription_key=subscription_key,
    time_range='2019-01/2019-03'
)

something is wrong :

Traceback (most recent call last):

  File ~/miniconda3/envs/sentinel1-flood-finder/lib/python3.11/site-packages/pandas/core/nanops.py:1703 in _ensure_numeric
    x = float(x)

TypeError: float() argument must be a string or a real number, not 'datetime.datetime'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  Cell In[5], line 4
    processor = FloodProcessor(

  File ~/miniconda3/envs/sentinel1-flood-finder/lib/python3.11/site-packages/flood_finder/floodprocessor.py:89 in __init__
    self.finder = WaterFinder(

  File ~/miniconda3/envs/sentinel1-flood-finder/lib/python3.11/site-packages/flood_finder/waterfinder.py:89 in __init__
    self.s1imagery = self.image_finder.get_s1_images(

  File ~/miniconda3/envs/sentinel1-flood-finder/lib/python3.11/site-packages/flood_finder/imagery.py:393 in get_s1_images
    return S1Imagery(items, aoi, lee_size, shape, group_items=group_items)

  File ~/miniconda3/envs/sentinel1-flood-finder/lib/python3.11/site-packages/flood_finder/imagery.py:113 in __init__
    self.df, self.groups = S1Imagery.create_grouped_df(

  File ~/miniconda3/envs/sentinel1-flood-finder/lib/python3.11/site-packages/flood_finder/imagery.py:295 in create_grouped_df
    df.loc[idx, "mean_datetime"] = subframe["datetime"].mean()

  File ~/miniconda3/envs/sentinel1-flood-finder/lib/python3.11/site-packages/pandas/core/series.py:6549 in mean
    return NDFrame.mean(self, axis, skipna, numeric_only, **kwargs)

  File ~/miniconda3/envs/sentinel1-flood-finder/lib/python3.11/site-packages/pandas/core/generic.py:12420 in mean
    return self._stat_function(

  File ~/miniconda3/envs/sentinel1-flood-finder/lib/python3.11/site-packages/pandas/core/generic.py:12377 in _stat_function
    return self._reduce(

  File ~/miniconda3/envs/sentinel1-flood-finder/lib/python3.11/site-packages/pandas/core/series.py:6457 in _reduce
    return op(delegate, skipna=skipna, **kwds)

  File ~/miniconda3/envs/sentinel1-flood-finder/lib/python3.11/site-packages/pandas/core/nanops.py:147 in f
    result = alt(values, axis=axis, skipna=skipna, **kwds)

  File ~/miniconda3/envs/sentinel1-flood-finder/lib/python3.11/site-packages/pandas/core/nanops.py:404 in new_func
    result = func(values, axis=axis, skipna=skipna, mask=mask, **kwargs)

  File ~/miniconda3/envs/sentinel1-flood-finder/lib/python3.11/site-packages/pandas/core/nanops.py:720 in nanmean
    the_sum = _ensure_numeric(the_sum)

  File ~/miniconda3/envs/sentinel1-flood-finder/lib/python3.11/site-packages/pandas/core/nanops.py:1707 in _ensure_numeric
    x = complex(x)

TypeError: complex() first argument must be a string or a number, not 'datetime.datetime'

**Comment by cordmaur** [comment]
Hi @Jiangchao3 , 

Thank you for your comments and interest in the package. 
I re-run the notebook here it it's working. From the error stack it seems something with `pandas` version. 

Can you check the version you are used and pin it to 2.0.2. 
Another alternative (easier, I think) is to use the docker I use in the .devcontainer file.

**Comment by Jiangchao3** [comment]
@cordmaur thanks for your great suggestion, the default installed pandas is latest 2.2.2, after i reinstall a 2.0.2 version, the introduction example can works well. many thanks for your help.

I will keep exploring your toolbox. Hope you have a nice day.
